//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TCPServer
{
    using System;
    using System.Collections.Generic;
    
    public partial class RfIdUser
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public RfIdUser()
        {
            this.EntryLog = new HashSet<EntryLog>();
        }
    
        public int IDRfIdUser { get; set; }
        public Nullable<int> UserId { get; set; }
        public Nullable<int> CardId { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EntryLog> EntryLog { get; set; }
        public virtual RfIdCard RfIdCard { get; set; }
    }
}
