//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RFIDLogger
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public User()
        {
            this.RfIdUser = new HashSet<RfIdUser>();
        }
    
        public int IDUser { get; set; }
        public string Name { get; set; }
        public string Surname { get; set; }
        public string OIB { get; set; }
        public string Address { get; set; }

        public string DisplayedName { get { return Surname + " " + Name; } }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RfIdUser> RfIdUser { get; set; }
    }
}
